-- Extended personal-profile fields on User. All optional / nullable.
-- Idempotent: safe to run on every deploy.
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "middleName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "preferredName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pronouns" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maritalStatus" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nationality" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "secondaryPhone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "secondaryEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "addressLine2" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "stateRegion" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "occupation" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "employer" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "languages" TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emergencyContactName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emergencyContactPhone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emergencyContactRelationship" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "linkedinUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twitterUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "facebookUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "heightCm" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "weightKg" DOUBLE PRECISION;
