// AUTO-GENERATED - real product photos sourced from Wikimedia Commons,
// downloaded to public/images/products/items/. Maps product name -> local image.
// Regenerate via scripts; do not hand-edit individual entries.

export const PRODUCT_IMAGE_MAP: Record<string, string> = {
  "Adult Diapers Pack": "/images/products/items/adult-diapers-pack.jpg",
  "Adult Incontinence Pads": "/images/products/items/adult-incontinence-pads.jpg",
  "Amlodipine 5mg": "/images/products/items/amlodipine-5mg.png",
  "Amoxicillin 250mg": "/images/products/items/amoxicillin-250mg.jpg",
  "Antacid Tablets": "/images/products/items/antacid-tablets.jpg",
  "Anti-Blue Light Glasses": "/images/products/items/anti-blue-light-glasses.jpg",
  "Antibacterial Mouthwash": "/images/products/items/antibacterial-mouthwash.jpg",
  "Ashwagandha Root Extract 500mg": "/images/products/items/ashwagandha-root-extract-500mg.jpg",
  "Atorvastatin 10mg": "/images/products/items/atorvastatin-10mg.jpg",
  "Atorvastatin 20mg": "/images/products/items/atorvastatin-20mg.jpg",
  "B-Complex Vitamins": "/images/products/items/b-complex-vitamins.png",
  "Baby Monitor": "/images/products/items/baby-monitor.jpg",
  "Baby Shampoo": "/images/products/items/baby-shampoo.jpg",
  "Baby Sunscreen SPF50": "/images/products/items/baby-sunscreen-spf50.jpg",
  "Baby Thermometer": "/images/products/items/baby-thermometer.jpg",
  "Baby Wipes Pack": "/images/products/items/baby-wipes-pack.jpg",
  "Bed Rail": "/images/products/items/bed-rail.jpg",
  "Blood Glucose Strips": "/images/products/items/blood-glucose-strips.jpg",
  "Blood Glucose Test Strips (50s)": "/images/products/items/blood-glucose-test-strips.jpg",
  "Blood Pressure Monitor": "/images/products/items/blood-pressure-monitor.jpg",
  "Blue Light Blocking Glasses": "/images/products/items/blue-light-blocking-glasses.jpg",
  "Calcium + Vitamin D": "/images/products/items/calcium-vitamin-d.jpg",
  "Cetirizine 10mg": "/images/products/items/cetirizine-10mg.jpg",
  "Children\\": "/images/products/items/children.jpg",
  "Chlorhexidine Mouthwash 0.2%": "/images/products/items/chlorhexidine-mouthwash-0-2.jpg",
  "Ciprofloxacin 500mg": "/images/products/items/ciprofloxacin-500mg.png",
  "Collagen Peptides": "/images/products/items/collagen-peptides.jpg",
  "Collagen Powder": "/images/products/items/collagen-powder.png",
  "Compression Bandage": "/images/products/items/compression-bandage.jpg",
  "Contact Lens Solution": "/images/products/items/contact-lens-solution.jpg",
  "Cough Syrup": "/images/products/items/cough-syrup.png",
  "Creatine Monohydrate": "/images/products/items/creatine-monohydrate.jpg",
  "Daily Contact Lenses (30pk)": "/images/products/items/daily-contact-lenses.jpg",
  "Dental Floss Pack": "/images/products/items/dental-floss-pack.jpg",
  "Dental Floss Set": "/images/products/items/dental-floss-set.jpg",
  "Dental Mirror": "/images/products/items/dental-mirror.jpg",
  "Dental Night Guard": "/images/products/items/dental-night-guard.jpg",
  "Diaper Cream": "/images/products/items/diaper-cream.jpg",
  "Digital Blood Pressure Monitor": "/images/products/items/digital-blood-pressure-monitor.jpg",
  "Digital Thermometer": "/images/products/items/digital-thermometer.jpg",
  "Electric Toothbrush": "/images/products/items/electric-toothbrush.jpg",
  "Emergency Blanket": "/images/products/items/emergency-blanket.jpg",
  "Exercise Ball 65cm": "/images/products/items/exercise-ball-65cm.jpg",
  "Eye Drops": "/images/products/items/eye-drops.jpg",
  "Eye Drops (Dry Eye)": "/images/products/items/eye-drops.jpg",
  "Eye Vitamin Formula": "/images/products/items/eye-vitamin-formula.jpg",
  "Fiber Supplement": "/images/products/items/fiber-supplement.jpg",
  "First Aid Kit": "/images/products/items/first-aid-kit.jpg",
  "Fluoride Mouthwash": "/images/products/items/fluoride-mouthwash.jpg",
  "Foam Roller": "/images/products/items/foam-roller.jpg",
  "Foam Roller - Deep Tissue": "/images/products/items/foam-roller-deep-tissue.jpg",
  "Glucose Meter Kit": "/images/products/items/glucose-meter-kit.png",
  "Hand Sanitizer 500ml": "/images/products/items/hand-sanitizer-500ml.jpg",
  "Home Test Kit COVID": "/images/products/items/home-test-kit-covid.jpg",
  "Hot/Cold Pack": "/images/products/items/hot-cold-pack.jpg",
  "Hyaluronic Acid Moisturiser": "/images/products/items/hyaluronic-acid-moisturiser.png",
  "Ibuprofen 400mg": "/images/products/items/ibuprofen-400mg.png",
  "Ice/Heat Pack": "/images/products/items/ice-heat-pack.jpg",
  "Infant CPR & Safety": "/images/products/items/infant-cpr-safety.jpg",
  "Iron Supplement 65mg": "/images/products/items/iron-supplement-65mg.jpg",
  "Kids Fluoride Treatment": "/images/products/items/kids-fluoride-treatment.jpg",
  "Knee Support Brace": "/images/products/items/knee-support-brace.png",
  "Lens Cleaning Kit": "/images/products/items/lens-cleaning-kit.jpg",
  "Levothyroxine 50mcg": "/images/products/items/levothyroxine-50mcg.png",
  "Lisinopril 10mg": "/images/products/items/lisinopril-10mg.png",
  "Loperamide 2mg": "/images/products/items/loperamide-2mg.jpg",
  "Losartan 50mg": "/images/products/items/losartan-50mg.jpg",
  "Magnesium 400mg": "/images/products/items/magnesium-400mg.jpg",
  "Massage Ball": "/images/products/items/massage-ball.jpg",
  "Meal Plan Guide (Diabetes)": "/images/products/items/meal-plan-guide.jpg",
  "Meal Replacement Shake": "/images/products/items/meal-replacement-shake.jpg",
  "Metformin 500mg": "/images/products/items/metformin-500mg.png",
  "Multivitamin Complex": "/images/products/items/multivitamin-complex.jpg",
  "N95 Face Masks": "/images/products/items/n95-face-masks.jpg",
  "Neck Brace": "/images/products/items/neck-brace.jpg",
  "Niacinamide 10% Face Serum": "/images/products/items/niacinamide-10-face-serum.jpg",
  "Non-Slip Socks": "/images/products/items/non-slip-socks.jpg",
  "Omega-3 Fish Oil": "/images/products/items/omega-3-fish-oil.jpg",
  "Omeprazole 20mg": "/images/products/items/omeprazole-20mg.jpg",
  "Oral Rehydration Salts": "/images/products/items/oral-rehydration-salts.jpg",
  "Orthodontic Retainer": "/images/products/items/orthodontic-retainer.jpg",
  "Orthodontic Wax": "/images/products/items/orthodontic-wax.jpg",
  "Paracetamol 500mg": "/images/products/items/paracetamol-500mg.jpg",
  "Pill Organizer (Weekly)": "/images/products/items/pill-organizer.jpg",
  "Posture Corrector": "/images/products/items/posture-corrector.jpg",
  "Prednisone 5mg": "/images/products/items/prednisone-5mg.jpg",
  "Pregnancy Test Kit": "/images/products/items/pregnancy-test-kit.jpg",
  "Prescription Sunglasses": "/images/products/items/prescription-sunglasses.jpg",
  "Probiotic 50B CFU": "/images/products/items/probiotic-50b-cfu.jpg",
  "Probiotic Capsules": "/images/products/items/probiotic-capsules.jpg",
  "Progressive Reading Glasses": "/images/products/items/progressive-reading-glasses.jpg",
  "Protein Powder": "/images/products/items/protein-powder.jpg",
  "Protein Supplement (Whey)": "/images/products/items/protein-supplement.jpg",
  "Pulse Oximeter": "/images/products/items/pulse-oximeter.jpg",
  "Reading Glasses +1.5": "/images/products/items/reading-glasses-1-5.jpg",
  "Reading Glasses +2.0": "/images/products/items/reading-glasses-2-0.jpg",
  "Resistance Band Set": "/images/products/items/resistance-band-set.jpg",
  "Resistance Bands Set": "/images/products/items/resistance-bands-set.jpg",
  "Salbutamol Inhaler 100mcg": "/images/products/items/salbutamol-inhaler-100mcg.jpg",
  "Sensitive Toothpaste (Rx)": "/images/products/items/sensitive-toothpaste.jpg",
  "Sertraline 50mg": "/images/products/items/sertraline-50mg.jpg",
  "SPF 50+ Sunscreen Gel": "/images/products/items/spf-50-sunscreen-gel.jpg",
  "Stethoscope": "/images/products/items/stethoscope.jpg",
  "Surgical Gloves box": "/images/products/items/surgical-gloves-box.jpg",
  "Teeth Whitening Kit": "/images/products/items/teeth-whitening-kit.jpg",
  "TENS Machine": "/images/products/items/tens-machine.png",
  "TENS Unit": "/images/products/items/tens-unit.jpg",
  "Triphala Churna": "/images/products/items/triphala-churna.jpg",
  "Urine Test Strips": "/images/products/items/urine-test-strips.jpg",
  "Vitamin C 1000mg": "/images/products/items/vitamin-c-1000mg.jpg",
  "Vitamin D3 1000IU": "/images/products/items/vitamin-d3-1000iu.jpg",
  "Vitamin D3 Drops": "/images/products/items/vitamin-d3-drops.jpg",
  "Walking Aid (Foldable)": "/images/products/items/walking-aid.jpg",
  "Warfarin 5mg": "/images/products/items/warfarin-5mg.jpg",
  "Weight Management Shake": "/images/products/items/weight-management-shake.jpg",
  "Wheelchair Cushion": "/images/products/items/wheelchair-cushion.jpg",
  "Whey Protein Isolate - Vanilla": "/images/products/items/whey-protein-isolate-vanilla.jpg",
  "Wound Dressing Kit": "/images/products/items/wound-dressing-kit.jpg",
  "Wrist Splint": "/images/products/items/wrist-splint.jpg",
  "Zinc 50mg": "/images/products/items/zinc-50mg.jpg",
}

/** Real per-product image if we have one, else the provided category fallback (or null). */
export function productImage(name: string, fallback: string | null = null): string | null {
  return PRODUCT_IMAGE_MAP[name] ?? fallback
}
